import { UserProfile, Match, ConnectionRequest, Message, Report, AppSettings } from '../types';

export const INITIAL_INDORI_PROFILES: UserProfile[] = [
  {
    id: 'user_priya_24',
    name: 'Priya Sharma',
    email: 'priya.s@gmail.com',
    dob: '2002-04-15',
    age: 24,
    gender: 'female',
    interestedIn: 'men',
    city: 'Indore',
    isIndoreResident: true,
    isAdult: true,
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80',
    ],
    bio: 'Architect by day, Sarafa midnight foodie by night. Looking for someone to explore new aesthetic cafés in Vijay Nagar & debate about the best poha-jalebi joint in town ☕✨',
    occupation: 'Architect & Interior Designer',
    education: 'SGSITS Indore',
    height: "5'5\"",
    relationshipIntent: 'Long-term relationship',
    interests: ['Foodie 🍲', 'Art & Design 🎨', 'Café Hopping ☕', 'Photography 📸', 'Road Trips 🚗'],
    indoreInterests: ['Sarafa Food Walk 🌙', 'Chappan Dukan Poha 🍽️', 'Vijay Nagar Nightlife 🍸', 'Indori Poha-Jalebi Fan 🥨'],
    isVerified: true,
    verificationStatus: 'verified',
    isOnline: true,
    lastActive: new Date().toISOString(),
    location: {
      locality: 'Vijay Nagar',
      distanceKm: 2.5,
    },
    isPremium: true,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-03-25T14:30:00Z',
  },
  {
    id: 'user_aarav_25',
    name: 'Aarav Patel',
    email: 'aarav.patel@gmail.com',
    dob: '2001-08-20',
    age: 25,
    gender: 'male',
    interestedIn: 'women',
    city: 'Indore',
    isIndoreResident: true,
    isAdult: true,
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&auto=format&fit=crop&q=80',
    ],
    bio: 'Tech founder building from Super Corridor. Weekend cyclist, filter coffee enthusiast, and frequent visitor to Meghdoot Garden. If you know good music, we will get along great 🎧',
    occupation: 'Software Engineer & Startup Founder',
    education: 'IIT Indore / DAVV',
    height: "5'11\"",
    relationshipIntent: 'Coffee & Conversation',
    interests: ['Entrepreneurship 🚀', 'Fitness & Gym 💪', 'Music 🎵', 'Gaming 🎮', 'Books & Literature 📚'],
    indoreInterests: ['Super Corridor Drives 🛣️', 'Vijay Nagar Nightlife 🍸', 'Chappan Dukan Poha 🍽️', 'Bhawarkua Chai Adda ☕'],
    isVerified: true,
    verificationStatus: 'verified',
    isOnline: true,
    lastActive: new Date().toISOString(),
    location: {
      locality: 'Scheme 54 / Meghdoot',
      distanceKm: 3.8,
    },
    isPremium: false,
    createdAt: '2026-01-15T11:20:00Z',
    updatedAt: '2026-03-26T18:10:00Z',
  },
  {
    id: 'user_ananya_23',
    name: 'Ananya Joshi',
    email: 'ananya.j@gmail.com',
    dob: '2003-02-14',
    age: 23,
    gender: 'female',
    interestedIn: 'men',
    city: 'Indore',
    isIndoreResident: true,
    isAdult: true,
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&auto=format&fit=crop&q=80',
    ],
    bio: 'Marketing lead & classical dancer. Born and raised in Old Palasia. Always down for spontaneous sunset drives to Ralamandal and ice cream runs at 56 🍨🌸',
    occupation: 'Brand Marketing Manager',
    education: 'Prestige Institute of Management (PIMR)',
    height: "5'4\"",
    relationshipIntent: 'Long-term relationship',
    interests: ['Travel ✈️', 'Cooking 🍳', 'Shopping 🛍️', 'Yoga & Wellness 🧘', 'Art & Design 🎨'],
    indoreInterests: ['Chappan Dukan Poha 🍽️', 'Ralamandal Sunset 🌅', 'Phoenix Citadel Spree 🛍️', 'Sev Lovers Clan 🌶️'],
    isVerified: true,
    verificationStatus: 'verified',
    isOnline: false,
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    location: {
      locality: 'Old & New Palasia',
      distanceKm: 1.8,
    },
    isPremium: true,
    createdAt: '2026-01-20T09:15:00Z',
    updatedAt: '2026-03-27T08:45:00Z',
  },
  {
    id: 'user_rohan_26',
    name: 'Rohan Mehra',
    email: 'rohan.mehra@gmail.com',
    dob: '2000-11-05',
    age: 26,
    gender: 'male',
    interestedIn: 'women',
    city: 'Indore',
    isIndoreResident: true,
    isAdult: true,
    photos: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    ],
    bio: 'Finance Analyst & weekend cricketer. Believes Indore has the highest happiness index in India. Looking for someone who laughs at terrible puns and enjoys live music nights 🎸',
    occupation: 'Senior Financial Analyst',
    education: 'IIM Indore',
    height: "6'0\"",
    relationshipIntent: 'Marriage / Matrimony',
    interests: ['Cricket 🏏', 'Movies 🎬', 'Foodie 🍲', 'Stand-up Comedy 🎤', 'Fitness & Gym 💪'],
    indoreInterests: ['Sarafa Food Walk 🌙', 'C21 Mall Hangouts 🏬', 'Vijay Nagar Nightlife 🍸', 'Patalpani & Mandu Trips 🏞️'],
    isVerified: true,
    verificationStatus: 'verified',
    isOnline: true,
    lastActive: new Date().toISOString(),
    location: {
      locality: 'Saket & Manoramaganj',
      distanceKm: 3.1,
    },
    isPremium: false,
    createdAt: '2026-01-22T15:40:00Z',
    updatedAt: '2026-03-27T12:00:00Z',
  },
  {
    id: 'user_ishita_24',
    name: 'Ishita Kapoor',
    email: 'ishita.k@gmail.com',
    dob: '2002-07-09',
    age: 24,
    gender: 'female',
    interestedIn: 'men',
    city: 'Indore',
    isIndoreResident: true,
    isAdult: true,
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80',
    ],
    bio: 'Fashion Stylist & Dog Mom. You can find me shopping at Phoenix Citadel or chilling at Saket cafés with my golden retriever. Let’s do a coffee date! ☕🐾',
    occupation: 'Fashion & Wardrobe Stylist',
    education: 'NIFT / Indore University',
    height: "5'6\"",
    relationshipIntent: 'Coffee & Conversation',
    interests: ['Pets & Dogs 🐕', 'Shopping 🛍️', 'Café Hopping ☕', 'Photography 📸', 'Music 🎵'],
    indoreInterests: ['Phoenix Citadel Spree 🛍️', 'Vijay Nagar Nightlife 🍸', 'Gulawat Lotus Valley 🪷', 'Chappan Dukan Poha 🍽️'],
    isVerified: true,
    verificationStatus: 'verified',
    isOnline: true,
    lastActive: new Date().toISOString(),
    location: {
      locality: 'Bypass / Phoenix Citadel',
      distanceKm: 5.2,
    },
    isPremium: false,
    createdAt: '2026-02-01T14:10:00Z',
    updatedAt: '2026-03-28T09:20:00Z',
  },
  {
    id: 'user_kabir_27',
    name: 'Kabir Verma',
    email: 'kabir.v@gmail.com',
    dob: '1999-05-18',
    age: 27,
    gender: 'male',
    interestedIn: 'women',
    city: 'Indore',
    isIndoreResident: true,
    isAdult: true,
    photos: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&auto=format&fit=crop&q=80',
    ],
    bio: 'Doctor by training, travel photographer by passion. Living in South Indore. Love heritage walks around Rajwada and road trips across Madhya Pradesh 🏰🚗',
    occupation: 'Resident Doctor (MGM Medical)',
    education: 'MGM Medical College Indore',
    height: "5'10\"",
    relationshipIntent: 'Long-term relationship',
    interests: ['Photography 📸', 'Hiking & Trekking 🏔️', 'Books & Literature 📚', 'Travel ✈️', 'Cooking 🍳'],
    indoreInterests: ['Rajwada Heritage 🏰', 'Patalpani & Mandu Trips 🏞️', 'Sarafa Food Walk 🌙', 'Sev Lovers Clan 🌶️'],
    isVerified: true,
    verificationStatus: 'verified',
    isOnline: false,
    lastActive: new Date(Date.now() - 7200000).toISOString(),
    location: {
      locality: 'Geeta Bhawan & Navlakha',
      distanceKm: 4.0,
    },
    isPremium: true,
    createdAt: '2026-02-10T16:45:00Z',
    updatedAt: '2026-03-28T11:00:00Z',
  },
  {
    id: 'user_tanmay_25',
    name: 'Tanmay Saxena',
    email: 'tanmay.s@gmail.com',
    dob: '2001-09-12',
    age: 25,
    gender: 'male',
    interestedIn: 'women',
    city: 'Indore',
    isIndoreResident: true,
    isAdult: true,
    photos: [
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    ],
    bio: 'Product Designer at a fintech company. Enthusiastic about UI/UX, filter brew, and Indori street food trails. Let’s grab a bite at Chappan! 🥨',
    occupation: 'Senior Product Designer',
    education: 'Symbiosis University Indore',
    height: "5'9\"",
    relationshipIntent: 'Coffee & Conversation',
    interests: ['Art & Design 🎨', 'Gaming 🎮', 'Café Hopping ☕', 'Music 🎵', 'Foodie 🍲'],
    indoreInterests: ['Chappan Dukan Poha 🍽️', 'Vijay Nagar Nightlife 🍸', 'C21 Mall Hangouts 🏬'],
    isVerified: true,
    verificationStatus: 'verified',
    isOnline: true,
    lastActive: new Date().toISOString(),
    location: {
      locality: 'Scheme 78 & Aranya',
      distanceKm: 2.1,
    },
    isPremium: false,
    createdAt: '2026-02-14T10:00:00Z',
    updatedAt: '2026-03-29T10:30:00Z',
  },
  {
    id: 'user_meera_23',
    name: 'Meera Trivedi',
    email: 'meera.t@gmail.com',
    dob: '2003-06-25',
    age: 23,
    gender: 'female',
    interestedIn: 'men',
    city: 'Indore',
    isIndoreResident: true,
    isAdult: true,
    photos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
    ],
    bio: 'Content creator & baker. If we match, I might bake you warm cinnamon rolls. Love quiet bookshops in Palasia and sunset walks around Meghdoot 🍰✨',
    occupation: 'Bakery Owner & Pastry Chef',
    education: 'Indore Institute of Management',
    height: "5'3\"",
    relationshipIntent: 'Long-term relationship',
    interests: ['Cooking 🍳', 'Books & Literature 📚', 'Music 🎵', 'Yoga & Wellness 🧘', 'Foodie 🍲'],
    indoreInterests: ['Meghdoot Garden Walk 🌳', 'Chappan Dukan Poha 🍽️', 'Sarafa Food Walk 🌙', 'Gulawat Lotus Valley 🪷'],
    isVerified: true,
    verificationStatus: 'verified',
    isOnline: true,
    lastActive: new Date().toISOString(),
    location: {
      locality: 'Annapurna & Sudama Nagar',
      distanceKm: 4.8,
    },
    isPremium: true,
    createdAt: '2026-02-20T12:00:00Z',
    updatedAt: '2026-03-29T15:00:00Z',
  }
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'match_priya_user',
    users: ['current_user_id', 'user_priya_24'],
    profiles: {
      current_user_id: {
        name: 'You',
        photo: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=800&auto=format&fit=crop&q=80',
        occupation: 'Professional',
        locality: 'Vijay Nagar',
      },
      user_priya_24: {
        name: 'Priya Sharma',
        photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
        occupation: 'Architect & Interior Designer',
        locality: 'Vijay Nagar',
      },
    },
    matchedAt: new Date(Date.now() - 86400000).toISOString(),
    lastMessage: 'Hey! Are you also into late-night Sarafa runs? 🌙',
    lastMessageTime: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastMessageSenderId: 'user_priya_24',
    unreadCount: {
      current_user_id: 1,
      user_priya_24: 0,
    },
  },
  {
    id: 'match_ananya_user',
    users: ['current_user_id', 'user_ananya_23'],
    profiles: {
      current_user_id: {
        name: 'You',
        photo: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=800&auto=format&fit=crop&q=80',
        occupation: 'Professional',
        locality: 'Vijay Nagar',
      },
      user_ananya_23: {
        name: 'Ananya Joshi',
        photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80',
        occupation: 'Brand Marketing Manager',
        locality: 'Old & New Palasia',
      },
    },
    matchedAt: new Date(Date.now() - 172800000).toISOString(),
    lastMessage: 'Let’s plan that coffee at Saket this Saturday! ☕',
    lastMessageTime: new Date(Date.now() - 86400000).toISOString(),
    lastMessageSenderId: 'current_user_id',
    unreadCount: {
      current_user_id: 0,
      user_ananya_23: 0,
    },
  },
];

export const INITIAL_CONNECTION_REQUESTS: ConnectionRequest[] = [
  {
    id: 'req_ishita_user',
    senderId: 'user_ishita_24',
    receiverId: 'current_user_id',
    senderProfile: {
      id: 'user_ishita_24',
      name: 'Ishita Kapoor',
      age: 24,
      photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
      occupation: 'Fashion & Wardrobe Stylist',
      bio: 'Fashion Stylist & Dog Mom. Love Phoenix Citadel and chill café dates.',
      locality: 'Bypass / Phoenix Citadel',
      indoreInterests: ['Phoenix Citadel Spree 🛍️', 'Vijay Nagar Nightlife 🍸'],
    },
    status: 'pending',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'req_meera_user',
    senderId: 'user_meera_23',
    receiverId: 'current_user_id',
    senderProfile: {
      id: 'user_meera_23',
      name: 'Meera Trivedi',
      age: 23,
      photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
      occupation: 'Bakery Owner & Pastry Chef',
      bio: 'Bakes fresh cinnamon rolls. Loves Meghdoot walks and Chappan Dukan.',
      locality: 'Annapurna & Sudama Nagar',
      indoreInterests: ['Meghdoot Garden Walk 🌳', 'Chappan Dukan Poha 🍽️'],
    },
    status: 'pending',
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
];

export const INITIAL_MESSAGES_PRIYA: Message[] = [
  {
    id: 'm1',
    conversationId: 'match_priya_user',
    senderId: 'user_priya_24',
    receiverId: 'current_user_id',
    text: 'Namaste! Great to match with a fellow Indori 😊',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    isRead: true,
    isDelivered: true,
  },
  {
    id: 'm2',
    conversationId: 'match_priya_user',
    senderId: 'current_user_id',
    receiverId: 'user_priya_24',
    text: 'Hey Priya! Absolutely, loved your bio. Architecture + Sarafa is the ultimate combo!',
    timestamp: new Date(Date.now() - 5400000).toISOString(),
    isRead: true,
    isDelivered: true,
  },
  {
    id: 'm3',
    conversationId: 'match_priya_user',
    senderId: 'user_priya_24',
    receiverId: 'current_user_id',
    text: 'Haha yes! Have you tried the bhutte ka kees at Joshi Dahi Bada recently? Best in town!',
    timestamp: new Date(Date.now() - 4000000).toISOString(),
    isRead: true,
    isDelivered: true,
  },
  {
    id: 'm4',
    conversationId: 'match_priya_user',
    senderId: 'user_priya_24',
    receiverId: 'current_user_id',
    text: 'Hey! Are you also into late-night Sarafa runs? 🌙',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    isRead: false,
    isDelivered: true,
  },
];

export const INITIAL_APP_SETTINGS: AppSettings = {
  premiumPrices: {
    monthly: 499,
    six_months: 1799,
    yearly: 2799,
  },
  freeDailyLikes: 15,
  freeDailySearches: 20,
  freeDailyRequests: 5,
  minAge: 18,
  announcement: '✨ Welcome to Indori Date! Strictly for Indore residents. Keep dating safe and local.',
};

export const INITIAL_REPORTS: Report[] = [
  {
    id: 'rep_01',
    reporterId: 'user_priya_24',
    reporterName: 'Priya Sharma',
    reportedUserId: 'user_fake_09',
    reportedUserName: 'Unknown Spammer',
    reason: 'Spam or commercial promotion',
    evidence: 'User was sending commercial real estate links repeatedly in chat.',
    status: 'pending',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'rep_02',
    reporterId: 'user_aarav_25',
    reporterName: 'Aarav Patel',
    reportedUserId: 'user_fake_11',
    reportedUserName: 'Fake Model Bot',
    reason: 'Fake profile / Impersonation',
    evidence: 'Stock photos used with unrealistic location data.',
    status: 'reviewed',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  }
];
